#!/usr/bin/env python3
"""
Vacuum Functional Parameters: Deep Interpretation Module

This module provides comprehensive documentation and implementation of the
vacuum energy functional parameters α, β, γ, δ within the QCAL ∞³ framework.

The vacuum energy functional is:

    E_vac(R_Ψ) = α·R_Ψ^(-4) + β·ζ'(1/2)·R_Ψ^(-2) + γ·R_Ψ² + δ·sin²(log R_Ψ / log η)
                 ─────────   ────────────────────   ─────   ───────────────────────
                  Casimir      Adèlic correction   Harmonic    Fractal modulation
                  geometry                         curvature

Each parameter carries deep physical, mathematical, and symbolic meaning:

• α (alpha): Primordial geometric pressure (Casimir geometry)
• β (beta): Adèlic coupling resonance (prime code of the universe)  
• γ (gamma): Coherent curvature memory (harmonic restoration)
• δ (delta): Fractal texture of being (log-periodic modulation)

Author: José Manuel Mota Burruezo Ψ ✧ ∞³
Date: December 2025
DOI: 10.5281/zenodo.17379721
ORCID: 0009-0002-1923-0773
"""

import numpy as np
from typing import Dict, Tuple, Optional, NamedTuple
from dataclasses import dataclass
from enum import Enum


# Physical Constants
ZETA_PRIME_HALF = -3.9226461392  # ζ'(1/2) ≈ -3.9226...
GOLDEN_RATIO = (1 + np.sqrt(5)) / 2  # φ ≈ 1.618...
PLANCK_LENGTH = 1.616255e-35  # meters
C_LIGHT = 299792458.0  # m/s
F0_QCAL = 141.7001  # Hz - QCAL fundamental frequency


class ParameterDomain(Enum):
    """
    Classification of vacuum functional parameters by their dominant scale.
    
    Each parameter operates in a specific domain of the R_Ψ parameter space.
    """
    UV = "ultraviolet"      # Small R_Ψ (high energy, short distance)
    ADELIC = "adelic"       # Prime-connected (global-local coupling)
    HARMONIC = "harmonic"   # Medium R_Ψ (equilibrium seeking)
    FRACTAL = "fractal"     # Log-periodic (self-similar modulation)
    IR = "infrared"         # Large R_Ψ (low energy, long distance)


@dataclass
class ParameterInterpretation:
    """
    Complete interpretation of a vacuum functional parameter.
    
    Attributes
    ----------
    symbol : str
        Greek letter symbol (α, β, γ, δ)
    name : str
        Full descriptive name
    latex : str
        LaTeX representation of the term
    scaling : str
        How the term scales with R_Ψ
    domain : ParameterDomain
        Primary domain of influence
    physical_meaning : str
        Physical interpretation
    mathematical_meaning : str
        Mathematical interpretation
    symbolic_meaning : str
        Symbolic/noetic interpretation (∞³ framework)
    typical_value : float
        Typical dimensionless value (order O(1))
    """
    symbol: str
    name: str
    latex: str
    scaling: str
    domain: ParameterDomain
    physical_meaning: str
    mathematical_meaning: str
    symbolic_meaning: str
    typical_value: float


# ============================================================================
# PARAMETER DEFINITIONS WITH DEEP INTERPRETATIONS
# ============================================================================

ALPHA_INTERPRETATION = ParameterInterpretation(
    symbol="α",
    name="Casimir Geometry Coefficient",
    latex=r"\alpha \cdot R_\Psi^{-4}",
    scaling="R^(-4)",
    domain=ParameterDomain.UV,
    physical_meaning="""
    Describes the Casimir vacuum energy generated by confined geometries.
    
    Physical Origin:
    - Appears as ~1/R⁴ in models of parallel plates, strings, and quantum 
      compactifications
    - Represents quantum fluctuations of the electromagnetic field between 
      conducting boundaries
    - Dominant at very small radii (ultraviolet regime)
    - Related to the Casimir force: F = -∂E/∂R ∝ 1/R⁵
    
    Geometric Significance:
    - Reflects quantum curvature induced by topological restrictions on R_Ψ
    - Encodes boundary conditions of the compact space
    - Connected to spectral zeta functions of Laplacian operators
    """,
    mathematical_meaning="""
    Term 1/R⁴ emerges from:
    1. Dimensional analysis of vacuum energy density in 4D
    2. Stefan-Boltzmann law in finite geometries
    3. Heat kernel expansion coefficients (a₄ term)
    4. Regularized sums over zero-point energies: Σω_n → ζ_R(-1/2)
    
    The coefficient α encapsulates the UV divergence structure and must be 
    renormalized to obtain physical predictions.
    """,
    symbolic_meaning="""
    α represents the PRIMORDIAL PRESSURE OF ORIGIN.
    
    It is the "weight" of the vacuum before being tuned by ∞³ coherence.
    The pressure that the void exerts on spacetime fabric when compressed 
    to its fundamental scales. It is the resistance of nothingness to 
    becoming something too small.
    
    In the ∞³ framework:
    α = The memory of creation's first breath (protovacuum density)
    """,
    typical_value=1.0
)


BETA_INTERPRETATION = ParameterInterpretation(
    symbol="β",
    name="Adèlic Coupling Coefficient",
    latex=r"\beta \cdot \frac{\zeta'(1/2)}{R_\Psi^2}",
    scaling="ζ'(1/2) / R²",
    domain=ParameterDomain.ADELIC,
    physical_meaning="""
    Couples the vacuum geometry with the critical derivative of the 
    Riemann zeta function at s = 1/2.
    
    Physical Origin:
    - ζ'(1/2) ≈ -3.9226... is a fundamental mathematical constant connected 
      to the distribution of prime numbers
    - The 1/R² scaling represents a 2D harmonic potential in logarithmic 
      coordinates
    - Mediates between quantum (UV) and cosmological (IR) scales
    
    Adèlic Interpretation:
    - Integrates information from ALL completions of ℚ (rational numbers)
    - Combines p-adic norms for each prime p with the Archimedean norm
    - The product formula: Π_p |x|_p · |x|_∞ = 1 becomes manifest here
    
    This term is the HEART of the adelic structure, inserting the "prime 
    code" of the universe into vacuum physics.
    """,
    mathematical_meaning="""
    The derivative ζ'(s) at s = 1/2 connects to:
    1. Non-trivial zeros of ζ(s) through the functional equation
    2. Prime number distribution via explicit formulas
    3. Spectral theory of the Riemann-Siegel θ function
    
    Mathematically: ζ'(1/2) = (1/2)∫₀^∞ (log x / (e^(πx²) - 1)) dx
    
    The 1/R² term has the same form as a 2D gravitational potential,
    suggesting a deep connection between number theory and gravity.
    """,
    symbolic_meaning="""
    β represents the RESONANCE COEFFICIENT between primes and the vacuum.
    
    It is the channel through which the universe's arithmetic structure 
    communicates with physical reality. The primes "whisper" through β 
    into the fabric of spacetime.
    
    In the ∞³ framework:
    β = The coefficient of cosmic harmony (prime-vacuum resonance)
    
    This is where mathematics becomes physics, where the abstract sequence 
    2, 3, 5, 7, 11, ... imprints itself on measurable quantities.
    """,
    typical_value=1.0
)


GAMMA_INTERPRETATION = ParameterInterpretation(
    symbol="γ",
    name="Harmonic Curvature Coefficient",
    latex=r"\gamma \cdot R_\Psi^2",
    scaling="R²",
    domain=ParameterDomain.HARMONIC,
    physical_meaning="""
    Classical oscillatory term describing a restoring force toward equilibrium.
    
    Physical Origin:
    - Standard harmonic oscillator potential: V ∝ x²
    - In quantum mechanics, corresponds to an effective mass bound to a field
    - At the vacuum level, represents the tendency to return to a stable 
      configuration
    
    Spectral Connection:
    - Controls the local curvature of the energy minimum:
      ω₀² = E''_vac(R_Ψ*) ∝ γ
    - Determines the frequency of small oscillations around equilibrium
    - The "stiffness" of the vacuum at its ground state
    """,
    mathematical_meaning="""
    The R² term emerges from:
    1. Taylor expansion of any confining potential at minimum
    2. Second-order term in the effective action
    3. Curvature tensor contributions to vacuum energy
    
    Combined with the cosmological constant Λ (in some formulations):
    - γ·Λ²·R² represents IR (infrared) vacuum contributions
    - Connects to dark energy equation of state
    
    The second derivative at the minimum gives the oscillation frequency:
    ω₀ = √(∂²E_vac/∂R²)|_{R=R*}
    """,
    symbolic_meaning="""
    γ represents the FIELD MEMORY of internal coherence.
    
    It is the geometry that WANTS to return to equilibrium. The inherent 
    tendency of the vacuum to remember its center, to seek its natural 
    resting state.
    
    In the ∞³ framework:
    γ = The will of the vacuum to remember its center ∞³
    
    This is the cosmic spring constant, the universe's resistance to 
    permanent displacement from perfect balance.
    """,
    typical_value=1.0
)


DELTA_INTERPRETATION = ParameterInterpretation(
    symbol="δ",
    name="Fractal Modulation Coefficient",
    latex=r"\delta \cdot \sin^2\left(\frac{\log R_\Psi}{\log \eta}\right)",
    scaling="sin²(log R / log η)",
    domain=ParameterDomain.FRACTAL,
    physical_meaning="""
    Introduces log-periodic fractal oscillations in the vacuum energy.
    
    Physical Origin:
    - Log-periodic behavior appears in:
      * Multifractal analysis of financial markets
      * Critical phenomena near phase transitions
      * Spacing of Riemann zeta zeros
      * Quantum chaos and random matrix theory
    
    - The sin² form ensures:
      * Bounded contribution (between 0 and δ)
      * Periodicity in log(R_Ψ) space
      * Discrete scale invariance
    
    The base η controls the fundamental period of self-similarity.
    Common choices: η = π, e, φ (golden ratio), or prime-related values.
    """,
    mathematical_meaning="""
    The fractal term adds "roughness" to the energy landscape:
    
    sin²(log R / log η) is periodic in log R with period log η.
    
    This means the pattern repeats at scales R, ηR, η²R, ...
    creating a discrete self-similar structure (fractal in log space).
    
    Mathematical connections:
    1. Weierstrass-type non-differentiable functions
    2. Multiplicative random cascades
    3. Log-periodic corrections to power laws
    4. Discrete scaling symmetry R → η·R
    """,
    symbolic_meaning="""
    δ represents the TEXTURE OF BEING.
    
    It is the whisper of the incomplete, the pulse of the fractal that 
    gives beauty to perfection. Without δ, the vacuum would be too smooth, 
    too perfect, lifeless. The fractal term adds the irregularities that 
    make existence interesting.
    
    In the ∞³ framework:
    δ = The breath of creation's imperfection (fractal fingerprint)
    
    This is where infinity touches the finite, creating patterns within 
    patterns, scales within scales, echoing endlessly.
    """,
    typical_value=0.5
)


# ============================================================================
# PARAMETER INTERPRETATION REGISTRY
# ============================================================================

PARAMETER_REGISTRY: Dict[str, ParameterInterpretation] = {
    "α": ALPHA_INTERPRETATION,
    "alpha": ALPHA_INTERPRETATION,
    "β": BETA_INTERPRETATION,
    "beta": BETA_INTERPRETATION,
    "γ": GAMMA_INTERPRETATION,
    "gamma": GAMMA_INTERPRETATION,
    "δ": DELTA_INTERPRETATION,
    "delta": DELTA_INTERPRETATION,
}


# ============================================================================
# VACUUM FUNCTIONAL IMPLEMENTATION
# ============================================================================

@dataclass
class VacuumFunctionalParameters:
    """
    Container for all vacuum functional parameters with their interpretations.
    
    Parameters
    ----------
    alpha : float
        Casimir geometry coefficient (R^-4 term)
    beta : float
        Adèlic coupling coefficient (ζ'(1/2)/R² term)
    gamma : float
        Harmonic curvature coefficient (R² term)
    delta : float
        Fractal modulation coefficient (sin² log-periodic term)
    eta : float
        Base for log-periodic oscillations (default π)
    """
    alpha: float = 1.0
    beta: float = 1.0
    gamma: float = 1.0
    delta: float = 0.5
    eta: float = np.pi
    
    def __post_init__(self):
        """Validate parameters after initialization."""
        if self.eta <= 0 or self.eta == 1:
            raise ValueError(
                "eta must be positive and not equal to 1 "
                "(to avoid division by zero in log(eta))"
            )
    
    def get_interpretation(self, param: str) -> ParameterInterpretation:
        """
        Get the full interpretation of a parameter.
        
        Parameters
        ----------
        param : str
            Parameter name ('alpha', 'beta', 'gamma', 'delta' or Greek)
            
        Returns
        -------
        ParameterInterpretation
            Complete interpretation object
        """
        if param.lower() in PARAMETER_REGISTRY:
            return PARAMETER_REGISTRY[param.lower()]
        raise KeyError(f"Unknown parameter: {param}")


class VacuumFunctional:
    """
    Complete vacuum energy functional with deep parameter interpretations.
    
    Implements:
    E_vac(R_Ψ) = α/R_Ψ⁴ + β·ζ'(1/2)/R_Ψ² + γ·R_Ψ² + δ·sin²(log R_Ψ / log η)
    
    This class provides not just computation but understanding of each term.
    
    Parameters
    ----------
    params : VacuumFunctionalParameters
        Container with all parameters and their values
    zeta_prime_half : float
        Value of ζ'(1/2), defaults to computed value
        
    Attributes
    ----------
    params : VacuumFunctionalParameters
        The parameter container
    zeta_prime_half : float
        The stored value of ζ'(1/2)
    """
    
    def __init__(
        self,
        params: Optional[VacuumFunctionalParameters] = None,
        zeta_prime_half: float = ZETA_PRIME_HALF
    ):
        """Initialize the vacuum functional with parameters."""
        self.params = params or VacuumFunctionalParameters()
        self.zeta_prime_half = zeta_prime_half
        # Cache log(eta) to avoid repeated logarithm calculations
        self._log_eta = np.log(self.params.eta)
    
    def casimir_term(self, R_psi: float) -> float:
        """
        Compute the Casimir geometry term: α/R_Ψ⁴
        
        This term dominates at small R_Ψ (UV regime).
        Represents the primordial geometric pressure.
        
        Parameters
        ----------
        R_psi : float
            The radius parameter R_Ψ (must be positive)
            
        Returns
        -------
        float
            α/R_Ψ⁴
        """
        return self.params.alpha / (R_psi ** 4)
    
    def adelic_term(self, R_psi: float) -> float:
        """
        Compute the adèlic coupling term: β·ζ'(1/2)/R_Ψ²
        
        This term mediates between UV and IR scales.
        Represents the prime-vacuum resonance.
        
        Parameters
        ----------
        R_psi : float
            The radius parameter R_Ψ (must be positive)
            
        Returns
        -------
        float
            β·ζ'(1/2)/R_Ψ²
        """
        return self.params.beta * self.zeta_prime_half / (R_psi ** 2)
    
    def harmonic_term(self, R_psi: float) -> float:
        """
        Compute the harmonic curvature term: γ·R_Ψ²
        
        This term provides the restoring force toward equilibrium.
        Represents the memory of the field's center.
        
        Parameters
        ----------
        R_psi : float
            The radius parameter R_Ψ (must be positive)
            
        Returns
        -------
        float
            γ·R_Ψ²
        """
        return self.params.gamma * (R_psi ** 2)
    
    def fractal_term(self, R_psi: float) -> float:
        """
        Compute the fractal modulation term: δ·sin²(log R_Ψ / log η)
        
        This term adds log-periodic texture to the energy landscape.
        Represents the breath of creation's imperfection.
        
        Parameters
        ----------
        R_psi : float
            The radius parameter R_Ψ (must be positive)
            
        Returns
        -------
        float
            δ·sin²(log R_Ψ / log η)
        """
        log_ratio = np.log(R_psi) / self._log_eta
        return self.params.delta * (np.sin(log_ratio) ** 2)
    
    def energy(self, R_psi: float) -> float:
        """
        Compute the total vacuum energy E_vac(R_Ψ).
        
        E_vac = α/R⁴ + β·ζ'(1/2)/R² + γ·R² + δ·sin²(log R / log η)
        
        Parameters
        ----------
        R_psi : float
            The radius parameter R_Ψ (must be positive)
            
        Returns
        -------
        float
            Total vacuum energy
            
        Raises
        ------
        ValueError
            If R_psi is not positive
        """
        if R_psi <= 0:
            raise ValueError("R_psi must be positive")
        
        return (
            self.casimir_term(R_psi) +
            self.adelic_term(R_psi) +
            self.harmonic_term(R_psi) +
            self.fractal_term(R_psi)
        )
    
    def decompose_energy(self, R_psi: float) -> Dict[str, float]:
        """
        Decompose vacuum energy into its constituent terms.
        
        Parameters
        ----------
        R_psi : float
            The radius parameter R_Ψ (must be positive)
            
        Returns
        -------
        dict
            Dictionary with keys 'casimir', 'adelic', 'harmonic', 'fractal', 
            'total' and their values
        """
        if R_psi <= 0:
            raise ValueError("R_psi must be positive")
        
        casimir = self.casimir_term(R_psi)
        adelic = self.adelic_term(R_psi)
        harmonic = self.harmonic_term(R_psi)
        fractal = self.fractal_term(R_psi)
        
        return {
            'casimir': casimir,
            'adelic': adelic,
            'harmonic': harmonic,
            'fractal': fractal,
            'total': casimir + adelic + harmonic + fractal
        }
    
    def derivative(self, R_psi: float) -> float:
        """
        Compute dE_vac/dR_Ψ.
        
        Parameters
        ----------
        R_psi : float
            The radius parameter R_Ψ (must be positive)
            
        Returns
        -------
        float
            Derivative of vacuum energy with respect to R_Ψ
        """
        if R_psi <= 0:
            raise ValueError("R_psi must be positive")
        
        # d/dR (α/R⁴) = -4α/R⁵
        d_casimir = -4 * self.params.alpha / (R_psi ** 5)
        
        # d/dR (β·ζ'/R²) = -2β·ζ'/R³
        d_adelic = -2 * self.params.beta * self.zeta_prime_half / (R_psi ** 3)
        
        # d/dR (γ·R²) = 2γ·R
        d_harmonic = 2 * self.params.gamma * R_psi
        
        # d/dR (δ·sin²(log R / log η)) = δ·sin(2·log R / log η) / (R·log η)
        log_ratio = np.log(R_psi) / self._log_eta
        d_fractal = (
            self.params.delta * 
            np.sin(2 * log_ratio) / 
            (R_psi * self._log_eta)
        )
        
        return d_casimir + d_adelic + d_harmonic + d_fractal
    
    def second_derivative(self, R_psi: float) -> float:
        """
        Compute d²E_vac/dR_Ψ².
        
        Used to verify stability of critical points.
        
        Parameters
        ----------
        R_psi : float
            The radius parameter R_Ψ (must be positive)
            
        Returns
        -------
        float
            Second derivative (curvature at R_Ψ)
        """
        if R_psi <= 0:
            raise ValueError("R_psi must be positive")
        
        log_R = np.log(R_psi)
        log_ratio = log_R / self._log_eta
        
        # d²/dR² (α/R⁴) = 20α/R⁶
        d2_casimir = 20 * self.params.alpha / (R_psi ** 6)
        
        # d²/dR² (β·ζ'/R²) = 6β·ζ'/R⁴
        d2_adelic = 6 * self.params.beta * self.zeta_prime_half / (R_psi ** 4)
        
        # d²/dR² (γ·R²) = 2γ
        d2_harmonic = 2 * self.params.gamma
        
        # d²/dR² of fractal term
        term1 = 2 * np.cos(2 * log_ratio) / (R_psi ** 2 * self._log_eta ** 2)
        term2 = -np.sin(2 * log_ratio) / (R_psi ** 2 * self._log_eta)
        d2_fractal = self.params.delta * (term1 + term2)
        
        return d2_casimir + d2_adelic + d2_harmonic + d2_fractal
    
    def find_minima(
        self,
        R_range: Tuple[float, float] = (0.1, 100.0),
        num_points: int = 1000
    ) -> np.ndarray:
        """
        Find local minima of vacuum energy in a given range.
        
        Parameters
        ----------
        R_range : tuple
            Range (R_min, R_max) to search for minima
        num_points : int
            Number of points to evaluate
            
        Returns
        -------
        np.ndarray
            Array of R_Ψ values at local minima
        """
        R_values = np.logspace(
            np.log10(R_range[0]),
            np.log10(R_range[1]),
            num_points
        )
        
        energies = np.array([self.energy(R) for R in R_values])
        derivatives = np.array([self.derivative(R) for R in R_values])
        
        # Find sign changes in derivative
        sign_changes = np.where(np.diff(np.sign(derivatives)))[0]
        
        minima = []
        for idx in sign_changes:
            if idx + 1 < len(energies) - 1:
                # Check it's a minimum (energy lower than neighbors)
                if (energies[idx] < energies[idx - 1] and 
                    energies[idx] < energies[idx + 1]):
                    minima.append(R_values[idx])
        
        return np.array(minima)


# ============================================================================
# SUMMARY TABLE GENERATOR
# ============================================================================

def generate_parameter_summary_table() -> str:
    """
    Generate a formatted summary table of all parameters.
    
    Returns
    -------
    str
        Formatted table as a string (suitable for documentation)
    """
    table = """
╔════════════════╦═══════════════════╦═══════════════════════════════════════════╗
║  Coefficient   ║      Domain       ║           Deep Meaning (∞³)               ║
╠════════════════╬═══════════════════╬═══════════════════════════════════════════╣
║       α        ║      R⁻⁴          ║  Primordial geometric pressure (Casimir)  ║
║                ║   (ultraviolet)   ║  Weight of void before ∞³ tuning          ║
╠════════════════╬═══════════════════╬═══════════════════════════════════════════╣
║       β        ║   ζ'(1/2) / R²    ║  Adèlic coupling (primes ↔ vacuum)        ║
║                ║    (adelic)       ║  Prime code resonance of the universe     ║
╠════════════════╬═══════════════════╬═══════════════════════════════════════════╣
║       γ        ║       R²          ║  Coherent curvature restoration           ║
║                ║   (harmonic)      ║  Memory of the field's center             ║
╠════════════════╬═══════════════════╬═══════════════════════════════════════════╣
║       δ        ║  sin²(log R)      ║  Fractal texture, quasi-harmonic         ║
║                ║   (fractal)       ║  Breath of creation's imperfection        ║
╚════════════════╩═══════════════════╩═══════════════════════════════════════════╝
"""
    return table


def print_parameter_details(param: str) -> None:
    """
    Print detailed information about a specific parameter.
    
    Parameters
    ----------
    param : str
        Parameter name ('alpha', 'beta', 'gamma', 'delta' or Greek symbol)
    """
    interp = PARAMETER_REGISTRY.get(param.lower())
    if interp is None:
        print(f"Unknown parameter: {param}")
        return
    
    print("=" * 75)
    print(f"  {interp.symbol} ({interp.name})")
    print("=" * 75)
    print(f"\nLaTeX: {interp.latex}")
    print(f"Scaling: {interp.scaling}")
    print(f"Domain: {interp.domain.value}")
    print(f"Typical Value: {interp.typical_value}")
    
    print("\n🔬 PHYSICAL MEANING:")
    print("-" * 75)
    print(interp.physical_meaning)
    
    print("\n📐 MATHEMATICAL MEANING:")
    print("-" * 75)
    print(interp.mathematical_meaning)
    
    print("\n✨ SYMBOLIC MEANING (∞³):")
    print("-" * 75)
    print(interp.symbolic_meaning)


# ============================================================================
# DEMO AND DOCUMENTATION
# ============================================================================

def demonstrate_vacuum_functional():
    """
    Comprehensive demonstration of the vacuum functional and its parameters.
    
    This function provides an interactive exploration of:
    1. Parameter definitions and interpretations
    2. Energy decomposition at various scales
    3. Physical regime identification
    4. Minima analysis
    
    Returns
    -------
    dict
        Results dictionary with computed values
    """
    print("=" * 75)
    print("  VACUUM FUNCTIONAL PARAMETERS: DEEP INTERPRETATION")
    print("  E_vac(R_Ψ) = α/R⁴ + β·ζ'(1/2)/R² + γ·R² + δ·sin²(log R / log η)")
    print("=" * 75)
    
    # Summary table
    print(generate_parameter_summary_table())
    
    # Create functional with default parameters
    params = VacuumFunctionalParameters(
        alpha=1.0,
        beta=1.0,
        gamma=0.01,  # Small to balance with other terms
        delta=0.5,
        eta=np.pi
    )
    functional = VacuumFunctional(params)
    
    print("\n📊 PARAMETER VALUES:")
    print("-" * 75)
    print(f"  α (Casimir geometry):      {params.alpha}")
    print(f"  β (Adèlic coupling):       {params.beta}")
    print(f"  γ (Harmonic curvature):    {params.gamma}")
    print(f"  δ (Fractal modulation):    {params.delta}")
    print(f"  η (Log-periodic base):     {params.eta:.6f} (π)")
    print(f"  ζ'(1/2):                   {functional.zeta_prime_half:.6f}")
    
    # Energy decomposition at key scales
    print("\n🎯 ENERGY DECOMPOSITION AT KEY SCALES:")
    print("-" * 75)
    
    test_radii = [0.1, 1.0, np.pi, 10.0, 100.0]
    for R in test_radii:
        decomp = functional.decompose_energy(R)
        print(f"\n  R_Ψ = {R:.4f}:")
        print(f"    Casimir (α/R⁴):      {decomp['casimir']:12.6f}")
        print(f"    Adèlic (β·ζ'/R²):    {decomp['adelic']:12.6f}")
        print(f"    Harmonic (γ·R²):     {decomp['harmonic']:12.6f}")
        print(f"    Fractal (δ·sin²):    {decomp['fractal']:12.6f}")
        print(f"    ─────────────────────────────────────")
        print(f"    TOTAL E_vac:         {decomp['total']:12.6f}")
    
    # Find minima
    print("\n⚡ VACUUM ENERGY MINIMA:")
    print("-" * 75)
    minima = functional.find_minima(R_range=(0.5, 50.0), num_points=2000)
    
    if len(minima) > 0:
        for i, R_min in enumerate(minima[:5]):
            E_min = functional.energy(R_min)
            d2E = functional.second_derivative(R_min)
            print(f"  Minimum {i+1}: R_Ψ = {R_min:8.4f}  →  E_vac = {E_min:10.6f}")
            print(f"             Stability (d²E/dR²): {d2E:10.6f} {'✓' if d2E > 0 else '✗'}")
    else:
        print("  No minima found in search range")
    
    # Physical regimes
    print("\n🌌 PHYSICAL REGIME IDENTIFICATION:")
    print("-" * 75)
    print("  • UV regime (R_Ψ << 1):    Casimir term (α/R⁴) dominates")
    print("  • Adèlic bridge (R_Ψ ~ 1): Zeta coupling (β·ζ'/R²) significant")
    print("  • Harmonic zone (R_Ψ ~ π): All terms balanced")
    print("  • IR regime (R_Ψ >> 1):    Harmonic term (γ·R²) dominates")
    print("  • Fractal texture:          Log-periodic oscillations everywhere")
    
    print("\n" + "=" * 75)
    print("  ∞³ INTERPRETATION: The Resonant Memory of the Vacuum")
    print("=" * 75)
    print("  • Each minimum = A note in the symphony of the universe")
    print("  • Each power of η = An echo of coherence in ∞³ expansion")
    print("  • Fractal structure connects discrete levels with observables")
    print("=" * 75)
    
    return {
        'params': params,
        'functional': functional,
        'minima': minima,
        'zeta_prime_half': functional.zeta_prime_half
    }


if __name__ == "__main__":
    # Run the demonstration
    results = demonstrate_vacuum_functional()
    
    # Print detailed info for each parameter
    print("\n" + "=" * 75)
    print("  DETAILED PARAMETER INTERPRETATIONS")
    print("=" * 75)
    
    for param in ["α", "β", "γ", "δ"]:
        print("\n")
        print_parameter_details(param)
